# Config of BukkitRadar
# For information about the settings, go to
# https://github.com/denniss17/BukkitRadar/blob/master/bukkitRadar/config.yml
playerradar:
   # The display name of the radar
   name: Players
   # The radius of this radar
   radius: 64
mobradar:
   # The display name of the radar
   name: Mobs
   # The radius of this radar
   radius: 32
   # Put down here the names of the mobs that needs to be displayed
   # The complete list of showable entities can be found here:
   # http://jd.bukkit.org/rb/apidocs/org/bukkit/entity/EntityType.html
   # Please use only uppercase
   mobs:
      CREEPER: '&aCreeper'
      CAVE_SPIDER: '&7Cave spider'
      ENDER_DRAGON: '&fEnder dragon'
      ENDERMAN: '&5Enderman'
      GHAST: '&fGhast'
      GIANT: '&3Giant'
      MAGMA_CUBE: '&6Magma cube'
      SILVERFISH: '&7Silverfish'
      SKELETON: '&fSkeleton'
      SLIME: '&aSlime'
      SPIDER: '&7Spider'
      WITCH: '&2Witch'
      WITHER: '&fWither'
      ZOMBIE: '&3Zombie'
      # Friendly mobs:
      # - BAT
      # - CHICKEN
      # - COW
      # - IRON_GOLEM
      # - MUSHROOM_COW
      # - OCELOT
      # - PIG
      # - PIG_ZOMBIE
      # - SHEEP
      # - SNOWMAN
      # - SQUID
      # - VILLAGER
      # - WOLF
# How often should the radars update? 20 = 1 second
radar_update_interval: 20
# Should the plugin check for updates?
check_updates: true
# With what interval should the plugin check for updates (in minutes)
check_updates_interval: 180 
# Individual messages can be changed here
messages:
   menu_header: '&7--=== &8[&2BukkitRadar&8] &7===--'
   menu_set: ' &f/bukkitradar &7set <player|mob>'
   menu_clear: ' &f/bukkitradar &7clear'
   menu_reload: ' &f/bukkitradar &7reload'
   menu_footer: ' &7You can also use &f/br &7or &f/radar'
   radar_player_set: '&8[&2BukkitRadar&8] &7Player radar set'
   radar_mob_set: '&8[&2BukkitRadar&8] &7Mob radar set'
   radar_type_not_valid: '&8[&2BukkitRadar&8] &eThat radar doesn`t exists!'
   radar_cleared: '&8[&2BukkitRadar&8] &7Radar cleared'
   plugin_reloaded: '&8[&2BukkitRadar&8] &7Plugin reloaded'
   error_not_a_player: '&8[&2BukkitRadar&8] &cYou have to be a player!'
   error_no_permission: '&8[&2BukkitRadar&8] &cYou don`t have permission to do this'